/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.chart.renderer.category.BarRenderer;
import Controller.CampaignControler;
import javax.swing.*;
import java.awt.*;
import java.util.Map;
import org.jfree.data.category.DefaultCategoryDataset;


public class ADashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */    
    private final CampaignControler controller;
    
    public ADashboard() {        
        controller = new CampaignControler();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        showBarChart();
        showLineChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_manageAgents = new necesario.MaterialButton();
        lbl_logout = new javax.swing.JLabel();
        btn_manageDoctors = new necesario.MaterialButton();
        btn_manageCampaigns = new necesario.MaterialButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 500, 290));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 500, 290));

        btn_manageAgents.setBackground(new java.awt.Color(255, 0, 0));
        btn_manageAgents.setForeground(new java.awt.Color(255, 255, 255));
        btn_manageAgents.setText("agents");
        btn_manageAgents.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btn_manageAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageAgentsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manageAgents, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 140, -1));

        lbl_logout.setText("           ");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_logoutMousePressed(evt);
            }
        });
        jPanel1.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, 40));

        btn_manageDoctors.setBackground(new java.awt.Color(255, 0, 0));
        btn_manageDoctors.setForeground(new java.awt.Color(255, 255, 255));
        btn_manageDoctors.setText("Doctors");
        btn_manageDoctors.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btn_manageDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageDoctorsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manageDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 590, 140, -1));

        btn_manageCampaigns.setBackground(new java.awt.Color(255, 0, 0));
        btn_manageCampaigns.setForeground(new java.awt.Color(255, 255, 255));
        btn_manageCampaigns.setText("Campaigns");
        btn_manageCampaigns.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btn_manageCampaigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageCampaignsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manageCampaigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 590, 140, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/2.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1296, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_manageAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageAgentsActionPerformed
        
        AMAgent manageAgent = new AMAgent();
        manageAgent.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_manageAgentsActionPerformed

    private void lbl_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMousePressed
                                          
    // Show confirmation dialog
    int response = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to logout?", 
        "Confirm Logout", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

    if (response == JOptionPane.YES_OPTION) {
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }


    }//GEN-LAST:event_lbl_logoutMousePressed

    private void btn_manageDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageDoctorsActionPerformed
        AMDoctor manageDoctor = new AMDoctor();
        manageDoctor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_manageDoctorsActionPerformed

    private void btn_manageCampaignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageCampaignsActionPerformed
        AMCompaign manageCampaign = new AMCompaign();
        manageCampaign.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_manageCampaignsActionPerformed
    public void showBarChart(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        Map<String, Integer> counts = controller.getCampaignStatus();
    
        dataset.setValue(counts.get("Pending"), "Campaign Status", "Pending");
        dataset.setValue(counts.get("Rejected"), "Campaign Status", "Rejected");
        dataset.setValue(counts.get("Accepted"), "Campaign Status", "Accepted");
        dataset.setValue(counts.get("Ongoing"), "Campaign Status", "Ongoing");
        dataset.setValue(counts.get("Completed"), "Campaign Status", "Completed");

        
        JFreeChart chart = ChartFactory.createBarChart("Campaign Status","Status","count", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(204,0,51);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        jPanel2.removeAll();
        jPanel2.add(barpChartPanel, BorderLayout.CENTER);
        jPanel2.validate();
        
        
    }
        public void showLineChart(){
        //create dataset for the graph
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        Map<String, Integer> campaignCounts = controller.getMonthlyCampaignCount();
        
        for (Map.Entry<String, Integer> entry : campaignCounts.entrySet()) {
            dataset.setValue(entry.getValue(), "Campaign Count", entry.getKey());
        }
        
        //create chart
        JFreeChart linechart = ChartFactory.createLineChart("Monthly Campaign Count","Month","Count", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        //create plot object
         CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();
       // lineCategoryPlot.setRangeGridlinePaint(Color.BLUE);
        lineCategoryPlot.setBackgroundPaint(Color.white);
        
        //create render object to change the moficy the line properties like color
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
        Color lineChartColor = new Color(204,0,51);
        lineRenderer.setSeriesPaint(0, lineChartColor);
        
         //create chartPanel to display chart(graph)
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        jPanel3.removeAll();
        jPanel3.add(lineChartPanel, BorderLayout.CENTER);
        jPanel3.validate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private necesario.MaterialButton btn_manageAgents;
    private necesario.MaterialButton btn_manageCampaigns;
    private necesario.MaterialButton btn_manageDoctors;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_logout;
    // End of variables declaration//GEN-END:variables
}
