/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Suneth
 */
public class AgDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AgentDashboard
     */
    public AgDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_campaigns = new necesario.MaterialButton();
        btn_eligibilityForms = new necesario.MaterialButton();
        background = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_campaigns.setBackground(new java.awt.Color(255, 0, 0));
        btn_campaigns.setForeground(new java.awt.Color(255, 255, 255));
        btn_campaigns.setText("Campaigns");
        btn_campaigns.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btn_campaigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_campaignsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_campaigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, 50));

        btn_eligibilityForms.setBackground(new java.awt.Color(255, 0, 0));
        btn_eligibilityForms.setForeground(new java.awt.Color(255, 255, 255));
        btn_eligibilityForms.setText("Eligibiity Forms");
        btn_eligibilityForms.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btn_eligibilityForms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eligibilityFormsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eligibilityForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/7.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        lbl_logout.setText("           ");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_logoutMousePressed(evt);
            }
        });
        jPanel1.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_campaignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_campaignsActionPerformed
       AgCampaign agCampaign = new AgCampaign();
       agCampaign.setVisible(true);
       dispose(); 
    }//GEN-LAST:event_btn_campaignsActionPerformed

    private void btn_eligibilityFormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eligibilityFormsActionPerformed
        AgEligibilityForm eligibilityForm = new AgEligibilityForm();
        eligibilityForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_eligibilityFormsActionPerformed

    private void lbl_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMousePressed

        int response = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_lbl_logoutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private necesario.MaterialButton btn_campaigns;
    private necesario.MaterialButton btn_eligibilityForms;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_logout;
    // End of variables declaration//GEN-END:variables
}
