/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.User;
import Controller.ManageDoctorController;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunet
 */
public class AMDoctor extends javax.swing.JFrame {
    /**
     * Creates new form AMDoctor
     */
    private final ManageDoctorController controller;
    public AMDoctor() {
        controller = new ManageDoctorController();
        this.setResizable(false);        
        initComponents();
        refreshTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_search = new necesario.MaterialButton();
        btn_save = new necesario.MaterialButton();
        txt_addConfirmPass = new rojerusan.RSPasswordTextPlaceHolder();
        txt_addPass = new rojerusan.RSPasswordTextPlaceHolder();
        list_doctorDetails = new javax.swing.JScrollPane();
        table_docList = new javax.swing.JTable();
        txt_searchDoctor = new app.bolivia.swing.JCTextField();
        btn_delete = new necesario.MaterialButton();
        btn_clearAll = new necesario.MaterialButton();
        btn_update = new necesario.MaterialButton();
        btn_add = new necesario.MaterialButton();
        txt_addFname = new app.bolivia.swing.JCTextField();
        txt_addLname = new app.bolivia.swing.JCTextField();
        txt_addContactNo = new app.bolivia.swing.JCTextField();
        txt_addUsername = new app.bolivia.swing.JCTextField();
        txt_updateContactNo = new app.bolivia.swing.JCTextField();
        txt_updateFname = new app.bolivia.swing.JCTextField();
        txt_updateUsername = new app.bolivia.swing.JCTextField();
        txt_updateLname = new app.bolivia.swing.JCTextField();
        btn_backDashboard = new necesario.RSMaterialButtonCircle();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_search.setBackground(new java.awt.Color(217, 217, 217));
        btn_search.setForeground(new java.awt.Color(153, 153, 153));
        btn_search.setText("Search");
        btn_search.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel2.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 285, 60, 30));

        btn_save.setBackground(new java.awt.Color(0, 153, 0));
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 570, 110, 40));

        txt_addConfirmPass.setBackground(new java.awt.Color(217, 217, 217));
        txt_addConfirmPass.setBorder(null);
        txt_addConfirmPass.setForeground(new java.awt.Color(0, 0, 0));
        txt_addConfirmPass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_addConfirmPass.setPhColor(new java.awt.Color(0, 0, 0));
        txt_addConfirmPass.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt_addConfirmPass.setSelectionColor(new java.awt.Color(204, 51, 0));
        txt_addConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addConfirmPassActionPerformed(evt);
            }
        });
        jPanel2.add(txt_addConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 544, 140, 32));

        txt_addPass.setBackground(new java.awt.Color(217, 217, 217));
        txt_addPass.setBorder(null);
        txt_addPass.setForeground(new java.awt.Color(0, 0, 0));
        txt_addPass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_addPass.setPhColor(new java.awt.Color(0, 0, 0));
        txt_addPass.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt_addPass.setSelectionColor(new java.awt.Color(204, 51, 0));
        txt_addPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addPassActionPerformed(evt);
            }
        });
        jPanel2.add(txt_addPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 496, 190, 32));

        list_doctorDetails.setBackground(new java.awt.Color(204, 204, 204));
        list_doctorDetails.setBorder(null);

        table_docList.setBackground(new java.awt.Color(255, 255, 255));
        table_docList.setForeground(new java.awt.Color(0, 0, 0));
        table_docList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Username", "Contact No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_docList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_docList.setGridColor(new java.awt.Color(255, 0, 0));
        table_docList.setRowHeight(25);
        table_docList.setSelectionBackground(new java.awt.Color(255, 0, 0));
        table_docList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table_docList.setShowGrid(false);
        table_docList.getTableHeader().setResizingAllowed(false);
        table_docList.getTableHeader().setReorderingAllowed(false);
        table_docList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_docListMouseClicked(evt);
            }
        });
        list_doctorDetails.setViewportView(table_docList);

        jPanel2.add(list_doctorDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 400, 450));

        txt_searchDoctor.setBackground(new java.awt.Color(217, 217, 217));
        txt_searchDoctor.setBorder(null);
        txt_searchDoctor.setForeground(new java.awt.Color(0, 0, 0));
        txt_searchDoctor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_searchDoctor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txt_searchDoctor.setPlaceholder("Search by Doctor Id");
        txt_searchDoctor.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_searchDoctor.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_searchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchDoctorActionPerformed(evt);
            }
        });
        jPanel2.add(txt_searchDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 150, 36));
        txt_searchDoctor.getAccessibleContext().setAccessibleName("");

        btn_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 110, 40));

        btn_clearAll.setBackground(new java.awt.Color(255, 0, 51));
        btn_clearAll.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearAll.setText("Clear all");
        btn_clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearAllActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 110, 40));

        btn_update.setBackground(new java.awt.Color(0, 51, 255));
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 110, 40));

        btn_add.setBackground(new java.awt.Color(0, 51, 255));
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 110, 40));

        txt_addFname.setBackground(new java.awt.Color(217, 217, 217));
        txt_addFname.setBorder(null);
        txt_addFname.setForeground(new java.awt.Color(0, 0, 0));
        txt_addFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_addFname.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_addFname.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_addFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addFnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_addFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 285, 180, -1));

        txt_addLname.setBackground(new java.awt.Color(217, 217, 217));
        txt_addLname.setBorder(null);
        txt_addLname.setForeground(new java.awt.Color(51, 51, 51));
        txt_addLname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_addLname.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_addLname.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_addLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addLnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_addLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 337, 180, -1));

        txt_addContactNo.setBackground(new java.awt.Color(217, 217, 217));
        txt_addContactNo.setBorder(null);
        txt_addContactNo.setForeground(new java.awt.Color(51, 51, 51));
        txt_addContactNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_addContactNo.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_addContactNo.setSelectionColor(new java.awt.Color(255, 0, 0));
        jPanel2.add(txt_addContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 170, -1));

        txt_addUsername.setBackground(new java.awt.Color(217, 217, 217));
        txt_addUsername.setBorder(null);
        txt_addUsername.setForeground(new java.awt.Color(51, 51, 51));
        txt_addUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_addUsername.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_addUsername.setSelectionColor(new java.awt.Color(255, 0, 0));
        txt_addUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_addUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 442, 180, -1));

        txt_updateContactNo.setEditable(false);
        txt_updateContactNo.setBackground(new java.awt.Color(217, 217, 217));
        txt_updateContactNo.setBorder(null);
        txt_updateContactNo.setForeground(new java.awt.Color(0, 0, 0));
        txt_updateContactNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_updateContactNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_updateContactNo.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_updateContactNo.setSelectionColor(new java.awt.Color(255, 0, 51));
        txt_updateContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateContactNoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_updateContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 459, 150, 30));

        txt_updateFname.setEditable(false);
        txt_updateFname.setBackground(new java.awt.Color(217, 217, 217));
        txt_updateFname.setBorder(null);
        txt_updateFname.setForeground(new java.awt.Color(0, 0, 0));
        txt_updateFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_updateFname.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_updateFname.setSelectionColor(new java.awt.Color(255, 0, 51));
        txt_updateFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateFnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_updateFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 353, 150, 30));

        txt_updateUsername.setEditable(false);
        txt_updateUsername.setBackground(new java.awt.Color(217, 217, 217));
        txt_updateUsername.setBorder(null);
        txt_updateUsername.setForeground(new java.awt.Color(0, 0, 0));
        txt_updateUsername.setCaretColor(new java.awt.Color(0, 0, 0));
        txt_updateUsername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_updateUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_updateUsername.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_updateUsername.setSelectionColor(new java.awt.Color(255, 0, 51));
        txt_updateUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_updateUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 514, 150, 30));

        txt_updateLname.setEditable(false);
        txt_updateLname.setBackground(new java.awt.Color(217, 217, 217));
        txt_updateLname.setBorder(null);
        txt_updateLname.setForeground(new java.awt.Color(0, 0, 0));
        txt_updateLname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_updateLname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_updateLname.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        txt_updateLname.setSelectionColor(new java.awt.Color(255, 0, 51));
        txt_updateLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateLnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_updateLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 405, 150, 30));

        btn_backDashboard.setBackground(new java.awt.Color(204, 0, 0));
        btn_backDashboard.setText("<");
        btn_backDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_backDashboard.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        btn_backDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backDashboardActionPerformed(evt);
            }
        });
        jPanel2.add(btn_backDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 60, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/5.png"))); // NOI18N
        jPanel2.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        setSize(new java.awt.Dimension(1296, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        
        String docId = txt_searchDoctor.getText();
        
        User doctor = controller.searchDoctor(docId);
        
        if(doctor != null){
            
            String fname = doctor.getFname();
            String lname = doctor.getLname();
            String contact = doctor.getContact();
            String username = doctor.getUsername();
                        
            txt_updateFname.setText(fname);
            txt_updateLname.setText(lname);
            txt_updateContactNo.setText(contact);
            txt_updateUsername.setText(username);
        } else{
            JOptionPane.showMessageDialog(null, "Invalid Doctor Id", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_searchActionPerformed
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
        String docId = txt_searchDoctor.getText();
        String fname = txt_updateFname.getText();
        String lname = txt_updateLname.getText();
        String contact = txt_updateContactNo.getText();
        String username = txt_updateUsername.getText();

        // Create a User object for the doctor
        User doctor = new User();
        doctor.setUser_id(docId);
        doctor.setFname(fname);
        doctor.setLname(lname);
        doctor.setContact(contact);
        doctor.setUsername(username);

        // Check if doctor ID is empty
        if (docId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Doctor ID is required.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Validate if contact number is valid (must start with 0 and have exactly 10 digits)
            if (!contact.matches("0[0-9]{9}")) {
                JOptionPane.showMessageDialog(null, "Invalid contact number. It must start with 0 and have exactly 10 digits.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // Confirmation dialog
                int response = JOptionPane.showConfirmDialog(
                        null, 
                        "Are you sure you want to update the doctor's information?", 
                        "Confirm Update", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE
                );

                // Proceed if user confirms
                if (response == JOptionPane.YES_OPTION) {
                    // Update doctor information
                    if (controller.updateDoctor(doctor)) {
                        JOptionPane.showMessageDialog(null, "Doctor updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Doctor ID.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Doctor update canceled.", "Canceled", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }

        // Clear input fields after the process is complete
        txt_searchDoctor.setText("");
        txt_updateFname.setText("");
        txt_updateLname.setText("");
        txt_updateContactNo.setText("");
        txt_updateUsername.setText("");

        // Make fields non-editable after update
        txt_updateFname.setEditable(false);
        txt_updateLname.setEditable(false);
        txt_updateContactNo.setEditable(false);
        txt_updateUsername.setEditable(false); 

        // Refresh the table to reflect changes
        refreshTable();

    }//GEN-LAST:event_btn_saveActionPerformed
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
        String docId = txt_searchDoctor.getText();
        
        if(docId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Doctor Id is required.", "Error", JOptionPane.ERROR_MESSAGE);
        } else{
            int response = JOptionPane.showConfirmDialog(
                null, 
                "Are you sure you want to delete this doctor?", 
                "Confirm Deletion", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
                );

            if (response == JOptionPane.YES_OPTION) {
                if (controller.deleteDoctor(docId)) {
                    JOptionPane.showMessageDialog(null, "Doctor Deleted Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Doctor Id.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Doctor deletion canceled.", "Canceled", JOptionPane.INFORMATION_MESSAGE);
            } 
        }
        
        txt_searchDoctor.setText("");
        txt_updateFname.setText("");
        txt_updateLname.setText("");
        txt_updateContactNo.setText("");
        txt_updateUsername.setText("");
        txt_updateFname.setEditable(false);
        txt_updateLname.setEditable(false);
        txt_updateContactNo.setEditable(false);
        txt_updateUsername.setEditable(false); 
        refreshTable();

    }//GEN-LAST:event_btn_deleteActionPerformed
    private void btn_clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearAllActionPerformed
        txt_addFname.setText("");
        txt_addLname.setText("");
        txt_addContactNo.setText("");
        txt_addUsername.setText("");
        txt_addPass.setText("");
        txt_addConfirmPass.setText("");
    }//GEN-LAST:event_btn_clearAllActionPerformed
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(!txt_updateFname.getText().equals("")){
            txt_updateFname.setEditable(true);
            txt_updateLname.setEditable(true);
            txt_updateContactNo.setEditable(true);
            txt_updateUsername.setEditable(true); 
        }
         
    }//GEN-LAST:event_btn_updateActionPerformed
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String fname = txt_addFname.getText();
        String lname = txt_addLname.getText();
        String contactNo = txt_addContactNo.getText();
        String username = txt_addUsername.getText();
        String password = String.valueOf(txt_addPass.getPassword());
        String confPassword = String.valueOf(txt_addConfirmPass.getPassword());

        // Check if any field is empty
        if(fname.isEmpty() || 
                lname.isEmpty() ||
                contactNo.isEmpty() ||
                username.isEmpty() ||
                password.isEmpty() ||
                confPassword.isEmpty()){

            JOptionPane.showMessageDialog(null, "All fields are required. Please fill in the necessary information.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Validate if passwords match
            if (!password.equals(confPassword)){
                JOptionPane.showMessageDialog(null, "Passwords do not match. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                txt_addPass.setText("");
                txt_addConfirmPass.setText("");
            } else {
                // Validate contact number format
                if (!contactNo.matches("0[0-9]{9}")) {
                    JOptionPane.showMessageDialog(null, "Invalid contact number. It must start with 0 and have exactly 10 digits.", "Error", JOptionPane.ERROR_MESSAGE);
                    txt_addContactNo.setText("");
                } else {
                    // Hash password and create a User object for the doctor
                    String hPassword = PasswordHashing.Hash(password);
                    User doctor = new User(username, hPassword, "doctor", fname, lname, contactNo);

                    // Confirmation dialog
                    int response = JOptionPane.showConfirmDialog(
                            null, 
                            "Are you sure you want to add this doctor?", 
                            "Confirm Addition", 
                            JOptionPane.YES_NO_OPTION, 
                            JOptionPane.QUESTION_MESSAGE
                    );

                    if (response == JOptionPane.YES_OPTION) {
                        // Attempt to add the doctor
                        if (controller.addDoctor(doctor)) {
                            JOptionPane.showMessageDialog(null, "Doctor Added Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "An error occurred while adding the doctor.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Doctor addition canceled.", "Canceled", JOptionPane.INFORMATION_MESSAGE);
                    }

                    // Clear input fields after submission
                    txt_addFname.setText("");        
                    txt_addLname.setText("");
                    txt_addContactNo.setText("");
                    txt_addUsername.setText("");
                    txt_addPass.setText("");
                    txt_addConfirmPass.setText("");   

                    // Refresh table
                    refreshTable();
                }
            }
        }
                
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_addUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addUsernameActionPerformed
    private void txt_addConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addConfirmPassActionPerformed
    private void txt_addPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addPassActionPerformed
    private void txt_updateContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_updateContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_updateContactNoActionPerformed
    private void btn_backDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backDashboardActionPerformed
        ADashboard dashboard = new ADashboard();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backDashboardActionPerformed
    private void txt_addFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addFnameActionPerformed
    }//GEN-LAST:event_txt_addFnameActionPerformed
    private void table_docListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_docListMouseClicked
        int row = table_docList.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            String docId = table_docList.getValueAt(row, 0).toString();
            String fname = table_docList.getValueAt(row, 1).toString();
            String lname = table_docList.getValueAt(row, 2).toString();
            String username = table_docList.getValueAt(row, 3).toString();
            String contact = table_docList.getValueAt(row, 4).toString();
            
            txt_searchDoctor.setText(docId);
            txt_updateFname.setText(fname);
            txt_updateLname.setText(lname);
            txt_updateContactNo.setText(contact);
            txt_updateUsername.setText(username);            
        }
    }//GEN-LAST:event_table_docListMouseClicked
    private void txt_updateFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_updateFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_updateFnameActionPerformed
    private void txt_updateUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_updateUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_updateUsernameActionPerformed
    private void txt_updateLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_updateLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_updateLnameActionPerformed
    private void txt_addLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addLnameActionPerformed
    private void txt_searchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchDoctorActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AMDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AMDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AMDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AMDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AMDoctor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private necesario.MaterialButton btn_add;
    private necesario.RSMaterialButtonCircle btn_backDashboard;
    private necesario.MaterialButton btn_clearAll;
    private necesario.MaterialButton btn_delete;
    private necesario.MaterialButton btn_save;
    private necesario.MaterialButton btn_search;
    private necesario.MaterialButton btn_update;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane list_doctorDetails;
    private javax.swing.JTable table_docList;
    private rojerusan.RSPasswordTextPlaceHolder txt_addConfirmPass;
    private app.bolivia.swing.JCTextField txt_addContactNo;
    private app.bolivia.swing.JCTextField txt_addFname;
    private app.bolivia.swing.JCTextField txt_addLname;
    private rojerusan.RSPasswordTextPlaceHolder txt_addPass;
    private app.bolivia.swing.JCTextField txt_addUsername;
    private app.bolivia.swing.JCTextField txt_searchDoctor;
    private app.bolivia.swing.JCTextField txt_updateContactNo;
    private app.bolivia.swing.JCTextField txt_updateFname;
    private app.bolivia.swing.JCTextField txt_updateLname;
    private app.bolivia.swing.JCTextField txt_updateUsername;
    // End of variables declaration//GEN-END:variables
    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel) table_docList.getModel();
        
        List<User> doctors = controller.getDoctors();
        model.setRowCount(0);
    
        for (User doctor : doctors) {
            Vector<Object> row = new Vector<>();
            row.add(doctor.getUser_id());
            row.add(doctor.getFname());
            row.add(doctor.getLname());
            row.add(doctor.getUsername());
            row.add(doctor.getContact());
            model.addRow(row);
        }
    }
}
