/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.SplashScreen;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicProgressBarUI;
import java.awt.Insets;
import java.awt.Graphics;

/**
 *
 * @author Suneth
 */
public class LoadingScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoadingScreen
     */
    public LoadingScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        customizeProgressBar();
        

    }
    private void customizeProgressBar() {
        progressBar.setUI(new BasicProgressBarUI() {
            @Override
            protected void paintString(Graphics g, int x, int y, int width, int height, int amountFull, Insets b) {
                super.paintString(g, x, y, width, height, amountFull, b);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        lbl_Percentage = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        bg_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setBackground(new java.awt.Color(255, 255, 255));
        progressBar.setForeground(new java.awt.Color(255, 51, 51));
        progressBar.setBorder(null);
        jPanel1.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 566, 1040, -1));

        lbl_Percentage.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lbl_Percentage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Percentage.setText("0%");
        jPanel1.add(lbl_Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 535, 60, -1));

        lbl_status.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        lbl_status.setText("Loading...");
        jPanel1.add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 535, 420, -1));

        bg_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/bg.png"))); // NOI18N
        jPanel1.add(bg_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        LoadingScreen load = new LoadingScreen();
        load.setVisible(true);
        try {
            
            for(int i = 0; i <= 100; i++){
                Thread.sleep(50);
                load.lbl_Percentage.setText(i + "%");
                
                if( i == 10){
                    load.lbl_status.setText("Turning On Modules...");
                } 
                
                if( i == 20){
                    load.lbl_status.setText("loading Modules...");
                }
                
                if( i == 50){
                    load.lbl_status.setText("Connecting to Database...");
                }
                if( i == 70){
                    load.lbl_status.setText("Connection Success...!");
                }
                
                if( i == 80){
                    load.lbl_status.setText("Launching Application...");
                }
                load.progressBar.setValue(i);
            }
            load.dispose();
            
            Waiting obj = new Waiting();
            obj.setVisible(true);
            try {
                Thread.sleep(2000);
                obj.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }
            Login login = new Login();
            login.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Percentage;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
